version: '2.2'

services:

  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - "25432:5432"
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata:
    name: grid-field-dbdata
